Vagrant.configure('2') do |config|
  config.vm.box = 'azure'

  config.vm.synced_folder ".", "/vagrant", disabled: true   # Para no tener que compartirlas

  # use local ssh key to connect to remote vagrant box
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.network "private_network", ip: "192.168.50.100"

  config.vm.provider :azure do |azure, override|

    # each of the below values will default to use the env vars named as below if not specified explicitly
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    # Configuración de la máquina virtual
    azure.location = 'uksouth'
    azure.resource_group_name = "recursos2"
    azure.vm_name = "mv2"
    azure.nsg_name = "nsg2"
    azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:latest'
    azure.vm_size = 'Standard_B1s' # Tamaño más básico
    azure.tcp_endpoints = 80 # Abrimos el puerto 80 (HTTP)

  end
  # Configuración de ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible_playbook.yml"
  end

end
